services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: wael
      POSTGRES_PASSWORD: wael
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: pmt
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"
    networks:
      - pmt-net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pmt-net
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
# Les sections suivantes sont destinées à déployer les services Frontend et Backend
# en utilisant des images Docker déjà créées et publiées sur Docker Hub.
# Si vous souhaitez utiliser ces images, décommentez cette partie et exécutez `docker-compose up`.
# Si des modifications ont été apportées au code, assurez-vous de reconstruire les images
# avant de déployer (voir README pour plus de détails).

#  pmt-api:
#    container_name: pmt-api
#    image: pmt/pmt:1.0.0
#    ports:
#      - 8088:8088
#    networks:
#      - pmt-net
#    depends_on:
#      - postgres
#  pmt-frontend:
#    container_name: pmt-frontend
#    image: pmt/pmt-frontend:1.0.0
#    ports:
#      - 8081:80
#    networks:
#      - pmt-net
#    depends_on:
#      - pmt-api
networks:
  pmt-net:
    driver: bridge

volumes:
  postgres:
  pgadmin: