/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskRequest } from '../../models/task-request';
import { TaskResponse } from '../../models/task-response';

export interface CreateTask$Params {
  projectId: number;
      body: TaskRequest
}

export function createTask(http: HttpClient, rootUrl: string, params: CreateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskResponse>> {
  const rb = new RequestBuilder(rootUrl, createTask.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskResponse>;
    })
  );
}

createTask.PATH = '/api/tasks/projectId={projectId}/tasks';
