/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface DeleteTask$Params {
  taskId: number;
}

export function deleteTask(
  http: HttpClient,
  rootUrl: string,
  params: DeleteTask$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, deleteTask.PATH, 'delete');
  if (params) {
    rb.path('taskId', params.taskId, {});
  }

  return http
    .request(
      rb.build({ responseType: 'text', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<string>;
      })
    );
}

deleteTask.PATH = '/api/tasks/{taskId}';
