/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskHistoryResponse } from '../../models/task-history-response';

export interface GetTaskModificationsForUserProjects$Params {
  page?: number;
  size?: number;
}

export function getTaskModificationsForUserProjects(http: HttpClient, rootUrl: string, params?: GetTaskModificationsForUserProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskHistoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getTaskModificationsForUserProjects.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskHistoryResponse>>;
    })
  );
}

getTaskModificationsForUserProjects.PATH = '/api/tasks/my-projects/history';
