/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskResponse } from '../../models/task-response';

export interface GetTaskById$Params {
  taskId: number;
}

export function getTaskById(http: HttpClient, rootUrl: string, params: GetTaskById$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskResponse>> {
  const rb = new RequestBuilder(rootUrl, getTaskById.PATH, 'get');
  if (params) {
    rb.path('taskId', params.taskId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskResponse>;
    })
  );
}

getTaskById.PATH = '/api/tasks/{taskId}';
