/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskResponse } from '../../models/task-response';

export interface GetTasksByPriority$Params {
  projectId: number;
  priority: 'LOW' | 'MEDIUM' | 'HIGH';
}

export function getTasksByPriority(http: HttpClient, rootUrl: string, params: GetTasksByPriority$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskResponse>>> {
  const rb = new RequestBuilder(rootUrl, getTasksByPriority.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.query('priority', params.priority, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskResponse>>;
    })
  );
}

getTasksByPriority.PATH = '/api/tasks/projectId={projectId}/tasksByPriority';
