/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InviteMemberRequest } from '../../models/invite-member-request';
import { ProjectResponse } from '../../models/project-response';

export interface InviteMemberToProject$Params {
  projectId: number;
      body: InviteMemberRequest
}

export function inviteMemberToProject(http: HttpClient, rootUrl: string, params: InviteMemberToProject$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectResponse>> {
  const rb = new RequestBuilder(rootUrl, inviteMemberToProject.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectResponse>;
    })
  );
}

inviteMemberToProject.PATH = '/api/projects/{projectId}/invite';
