/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponse } from '../models/user-response';
export interface AuthenticationResponse {
  token?: string;
  user?: UserResponse;
}
