/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectRequest {
  description: string;
  id?: number;
  name: string;
  startDate: string;
}
