/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskModifiedHistory } from '../models/task-modified-history';
import { User } from '../models/user';
export interface Task {
  assignedTo?: User;
  createdBy?: number;
  createdDate?: string;
  description?: string;
  dueDate?: string;
  histories?: Array<TaskModifiedHistory>;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  name?: string;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH';
  status?: 'TODO' | 'IN_PROGRESS' | 'DONE';
}
