/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskHistoryResponse {
  lastModifiedById?: number;
  lastModifiedByName?: string;
  lastModifiedDate?: string;
  modificationDescription?: string;
  projectName?: string;
  taskId?: number;
  taskName?: string;
}
