/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Task } from '../models/task';
import { User } from '../models/user';
export interface TaskModifiedHistory {
  createdBy?: number;
  createdDate?: string;
  description?: string;
  id?: number;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  task?: Task;
  user?: User;
}
