/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';
import { Task } from '../models/task';
import { TaskModifiedHistory } from '../models/task-modified-history';
export interface User {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  assignedTasks?: Array<Task>;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  fullName?: string;
  histories?: Array<TaskModifiedHistory>;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  nom?: string;
  password?: string;
  prenom?: string;
  roles?: Array<Role>;
  username?: string;
}
