/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string;
  id?: number;
  nom?: string;
  prenom?: string;
  role?: string;
}
