name: Project-management-tool Backend Pipeline

on:
  push:
    branches:
      - '*'
    paths:
      - 'project-management-backend/**'
      - 'docker-compose.yml'
      - '.github/workflows/*-backend.yml'
      - 'docker/backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Initialize and Update Submodules
        run: git submodule update --init --recursive

      - name: Verify Backend Submodule
        run: |
          ls -l project-management-backend
          ls -l project-management-backend/src || echo "Src folder not found"
          ls -l project-management-backend/pom.xml || echo "Pom.xml not found"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Prepare Docker Build Context
        run: |
          mkdir -p docker-build-context/project-management-backend
          cp -R project-management-backend/* docker-build-context/project-management-backend

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: docker-build-context
          file: docker/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pmt-api:latest
          build-args:
            APP_VERSION=1.0.0
